services:
  - type: web
    name: quiz-backend
    env: docker
    plan: free
    autoDeploy: true

    envVars:
      - key: DB_HOST
        value: tramway.proxy.rlwy.net
      - key: DB_PORT
        value: 48942
      - key: DB_NAME
        value: railway
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: rkLlVcbNgFjcUZMRnBUjkpkjqlqZkGLl
